//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.25 at 01:48:50 AM CET
//


package de.unipassau.medspace.common.config.general_wrapper;

import de.unipassau.medspace.common.rdf.Namespace;
import de.unipassau.medspace.common.register.Service;

import java.net.URL;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Services" type="{http://www.medspace.com/wrapper-config-specification}Services" minOccurs="0"/>
 *         &lt;element name="IndexDirectoy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Namespaces" type="{http://www.medspace.com/wrapper-config-specification}Namespaces" minOccurs="0"/>
 *         &lt;element name="OutputFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegisterUrl" type="{http://www.medspace.com/wrapper-config-specification}URL"/>
 *         &lt;element name="ConnectToRegister" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "services",
    "indexDirectoy",
    "namespaces",
    "outputFormat",
    "registerUrl",
    "connectToRegister"
})
@XmlRootElement(name = "Config")
public class Config {

    @XmlElement(name = "Description", required = true)
    protected String description;

    @XmlElement(name = "Services")
    @XmlJavaTypeAdapter(ServicesAdapter.class)
    protected List<Service> services;

    @XmlElement(name = "IndexDirectoy")
    protected String indexDirectoy;

    @XmlElement(name = "Namespaces")
    @XmlJavaTypeAdapter(NamespacesAdapter.class)
    protected Map<String, Namespace> namespaces;

    @XmlElement(name = "OutputFormat", required = true)
    protected String outputFormat;

    @XmlElement(name = "RegisterUrl", required = true, type = String.class)
    @XmlJavaTypeAdapter(RegisterUrlAdapter.class)
    protected URL registerUrl;

    @XmlElement(name = "ConnectToRegister")
    protected Boolean connectToRegister;

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the services property.
     *
     * @return
     *     possible object is
     *     {@link Services }
     *
     */
    public List<Service> getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     *
     * @param value
     *     allowed object is
     *     {@link Services }
     *
     */
    public void setServices(List<Service> value) {
        this.services = value;
    }

    /**
     * Gets the value of the indexDirectoy property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIndexDirectoy() {
        return indexDirectoy;
    }

    /**
     * Sets the value of the indexDirectoy property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIndexDirectoy(String value) {
        this.indexDirectoy = value;
    }

    /**
     * Gets the value of the namespaces property.
     *
     * @return
     *     possible object is
     *     {@link Namespaces }
     *
     */
    public Map<String, Namespace> getNamespaces() {
        return namespaces;
    }

    /**
     * Sets the value of the namespaces property.
     *
     * @param value
     *     allowed object is
     *     {@link Namespaces }
     *
     */
    public void setNamespaces(Map<String, Namespace> value) {
        this.namespaces = value;
    }

    /**
     * Gets the value of the outputFormat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOutputFormat() {
        return outputFormat;
    }

    /**
     * Sets the value of the outputFormat property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOutputFormat(String value) {
        this.outputFormat = value;
    }

    /**
     * Gets the value of the registerUrl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public URL getRegisterUrl() {
        return registerUrl;
    }

    /**
     * Sets the value of the registerUrl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRegisterUrl(URL value) {
        this.registerUrl = value;
    }

    /**
     * Gets the value of the connectToRegister property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isConnectToRegister() {
        return connectToRegister;
    }

    /**
     * Sets the value of the connectToRegister property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setConnectToRegister(Boolean value) {
        this.connectToRegister = value;
    }

}