//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.25 at 01:48:50 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.medspace.com/wrapper-config-specification", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.unipassau.medspace.common.config.general_wrapper;
