//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 11:50:25 PM CET 
//


package de.unipassau.medspace.common.config.general_wrapper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class RegisterUrlAdapter
    extends XmlAdapter<String, URL>
{


    public URL unmarshal(String value) throws MalformedURLException {
        return new URL(value);
    }

    public String marshal(URL value) throws Exception {
        return value.toString();
    }
}