//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.25 at 04:04:37 PM CET 
//


package de.unipassau.medspace.d2r.config.parsing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="DataTypePropertyBridge" type="{http://www.medspace.com/D2Rmap}DataTypePropertyBridge" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ObjectPropertyBridge" type="{http://www.medspace.com/D2Rmap}ObjectPropertyBridge" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="sql" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resourceIdColumns" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="baseURI" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassMap", propOrder = {
    "dataTypePropertyBridgeOrObjectPropertyBridge"
})
public class ClassMapParsing {

    @XmlElements({
        @XmlElement(name = "DataTypePropertyBridge", type = DataTypePropertyBridgeParsing.class),
        @XmlElement(name = "ObjectPropertyBridge", type = ObjectPropertyBridgeParsing.class)
    })
    protected List<BridgeParsing> dataTypePropertyBridgeOrObjectPropertyBridge;
    @XmlAttribute(name = "sql", required = true)
    protected String sql;
    @XmlAttribute(name = "resourceIdColumns", required = true)
    protected String resourceIdColumns;
    @XmlAttribute(name = "baseURI", required = true)
    protected String baseURI;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the dataTypePropertyBridgeOrObjectPropertyBridge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataTypePropertyBridgeOrObjectPropertyBridge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataTypePropertyBridgeOrObjectPropertyBridge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataTypePropertyBridgeParsing }
     * {@link ObjectPropertyBridgeParsing }
     * 
     * 
     */
    public List<BridgeParsing> getDataTypePropertyBridgeOrObjectPropertyBridge() {
        if (dataTypePropertyBridgeOrObjectPropertyBridge == null) {
            dataTypePropertyBridgeOrObjectPropertyBridge = new ArrayList<BridgeParsing>();
        }
        return this.dataTypePropertyBridgeOrObjectPropertyBridge;
    }

    /**
     * Gets the value of the sql property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSql() {
        return sql;
    }

    /**
     * Sets the value of the sql property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSql(String value) {
        this.sql = value;
    }

    /**
     * Gets the value of the resourceIdColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceIdColumns() {
        return resourceIdColumns;
    }

    /**
     * Sets the value of the resourceIdColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceIdColumns(String value) {
        this.resourceIdColumns = value;
    }

    /**
     * Gets the value of the baseURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseURI() {
        return baseURI;
    }

    /**
     * Sets the value of the baseURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseURI(String value) {
        this.baseURI = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
