//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.31 at 08:59:58 PM CEST 
//


package de.unipassau.medspace.d2r.config.parsing;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.unipassau.medspace.d2r.config.parsing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.unipassau.medspace.d2r.config.parsing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RootParsing }
     * 
     */
    public RootParsing createRootParsing() {
        return new RootParsing();
    }

    /**
     * Create an instance of {@link DBConnectionParsing }
     * 
     */
    public DBConnectionParsing createDBConnectionParsing() {
        return new DBConnectionParsing();
    }

    /**
     * Create an instance of {@link ObjectPropertyBridgeParsing }
     * 
     */
    public ObjectPropertyBridgeParsing createObjectPropertyBridgeParsing() {
        return new ObjectPropertyBridgeParsing();
    }

    /**
     * Create an instance of {@link DataSourcePropertyParsing }
     * 
     */
    public DataSourcePropertyParsing createDataSourcePropertyParsing() {
        return new DataSourcePropertyParsing();
    }

    /**
     * Create an instance of {@link DBAuthentificationParsing }
     * 
     */
    public DBAuthentificationParsing createDBAuthentificationParsing() {
        return new DBAuthentificationParsing();
    }

    /**
     * Create an instance of {@link DataTypePropertyBridgeParsing }
     * 
     */
    public DataTypePropertyBridgeParsing createDataTypePropertyBridgeParsing() {
        return new DataTypePropertyBridgeParsing();
    }

    /**
     * Create an instance of {@link ClassMapParsing }
     * 
     */
    public ClassMapParsing createClassMapParsing() {
        return new ClassMapParsing();
    }

    /**
     * Create an instance of {@link NamespaceParsing }
     * 
     */
    public NamespaceParsing createNamespaceParsing() {
        return new NamespaceParsing();
    }

}
