//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 09:38:02 PM CET 
//


package de.unipassau.medspace.d2r.config.parsing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Root element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Root">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="DBConnection" type="{http://www.medspace.com/D2Rmap}DBConnection"/>
 *           &lt;element name="Namespace" type="{http://www.medspace.com/D2Rmap}Namespace" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="ClassMap" type="{http://www.medspace.com/D2Rmap}ClassMap" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbConnection",
    "namespace",
    "classMap"
})
@XmlRootElement(name = "Root")
public class RootParsing {

    @XmlElement(name = "DBConnection", required = true)
    protected DBConnectionParsing dbConnection;
    @XmlElement(name = "Namespace")
    protected List<NamespaceParsing> namespace;
    @XmlElement(name = "ClassMap")
    protected List<ClassMapParsing> classMap;

    /**
     * Gets the value of the dbConnection property.
     * 
     * @return
     *     possible object is
     *     {@link DBConnectionParsing }
     *     
     */
    public DBConnectionParsing getDBConnection() {
        return dbConnection;
    }

    /**
     * Sets the value of the dbConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBConnectionParsing }
     *     
     */
    public void setDBConnection(DBConnectionParsing value) {
        this.dbConnection = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namespace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamespace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NamespaceParsing }
     * 
     * 
     */
    public List<NamespaceParsing> getNamespace() {
        if (namespace == null) {
            namespace = new ArrayList<NamespaceParsing>();
        }
        return this.namespace;
    }

    /**
     * Gets the value of the classMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassMapParsing }
     * 
     * 
     */
    public List<ClassMapParsing> getClassMap() {
        if (classMap == null) {
            classMap = new ArrayList<ClassMapParsing>();
        }
        return this.classMap;
    }

}
