//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.18 at 05:59:32 PM CET 
//


package de.unipassau.medspace.common.rdf.mapping;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.unipassau.medspace.common.rdf.mapping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.unipassau.medspace.common.rdf.mapping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObjectPropertyMapping }
     * 
     */
    public ObjectPropertyMapping createObjectPropertyMapping() {
        return new ObjectPropertyMapping();
    }

    /**
     * Create an instance of {@link ClassMapping }
     * 
     */
    public ClassMapping createClassMapping() {
        return new ClassMapping();
    }

    /**
     * Create an instance of {@link DataTypePropertyMapping }
     * 
     */
    public DataTypePropertyMapping createDataTypePropertyMapping() {
        return new DataTypePropertyMapping();
    }

    /**
     * Create an instance of {@link PropertyMapping }
     * 
     */
    public PropertyMapping createPropertyMapping() {
        return new PropertyMapping();
    }

    /**
     * Create an instance of {@link FileMapping }
     * 
     */
    public FileMapping createFileMapping() {
        return new FileMapping();
    }

    /**
     * Create an instance of {@link NamespaceMapping }
     * 
     */
    public NamespaceMapping createNamespaceMapping() {
        return new NamespaceMapping();
    }

}
