//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.02 at 12:36:13 AM CEST 
//


package de.unipassau.medspace.wrapper.image_wrapper.config.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import de.unipassau.medspace.common.rdf.mapping.ClassMapping;
import de.unipassau.medspace.common.rdf.mapping.DataTypePropertyMapping;
import de.unipassau.medspace.common.rdf.mapping.ObjectPropertyMapping;


/**
 * <p>Java class for Abnormality complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Abnormality">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.medspace.com/rdf-mapping}Class">
 *       &lt;sequence>
 *         &lt;element name="abnormality" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="calcification" type="{http://www.medspace.com/rdf-mapping}ObjectProperty"/>
 *         &lt;element name="mass" type="{http://www.medspace.com/rdf-mapping}ObjectProperty"/>
 *         &lt;element name="assessment" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="subtlety" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="pathology" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="totalOutlines" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Abnormality", propOrder = {
    "abnormality",
    "calcification",
    "mass",
    "assessment",
    "subtlety",
    "pathology",
    "totalOutlines"
})
public class AbnormalityMapping
    extends ClassMapping
{

    @XmlElement(required = true)
    protected DataTypePropertyMapping abnormality;
    @XmlElement(required = true)
    protected ObjectPropertyMapping calcification;
    @XmlElement(required = true)
    protected ObjectPropertyMapping mass;
    @XmlElement(required = true)
    protected DataTypePropertyMapping assessment;
    @XmlElement(required = true)
    protected DataTypePropertyMapping subtlety;
    @XmlElement(required = true)
    protected DataTypePropertyMapping pathology;
    @XmlElement(required = true)
    protected DataTypePropertyMapping totalOutlines;

    /**
     * Gets the value of the abnormality property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getAbnormality() {
        return abnormality;
    }

    /**
     * Sets the value of the abnormality property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setAbnormality(DataTypePropertyMapping value) {
        this.abnormality = value;
    }

    /**
     * Gets the value of the calcification property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public ObjectPropertyMapping getCalcification() {
        return calcification;
    }

    /**
     * Sets the value of the calcification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public void setCalcification(ObjectPropertyMapping value) {
        this.calcification = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public ObjectPropertyMapping getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public void setMass(ObjectPropertyMapping value) {
        this.mass = value;
    }

    /**
     * Gets the value of the assessment property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getAssessment() {
        return assessment;
    }

    /**
     * Sets the value of the assessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setAssessment(DataTypePropertyMapping value) {
        this.assessment = value;
    }

    /**
     * Gets the value of the subtlety property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getSubtlety() {
        return subtlety;
    }

    /**
     * Sets the value of the subtlety property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setSubtlety(DataTypePropertyMapping value) {
        this.subtlety = value;
    }

    /**
     * Gets the value of the pathology property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getPathology() {
        return pathology;
    }

    /**
     * Sets the value of the pathology property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setPathology(DataTypePropertyMapping value) {
        this.pathology = value;
    }

    /**
     * Gets the value of the totalOutlines property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getTotalOutlines() {
        return totalOutlines;
    }

    /**
     * Sets the value of the totalOutlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setTotalOutlines(DataTypePropertyMapping value) {
        this.totalOutlines = value;
    }

}
