//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.18 at 05:57:11 PM CET 
//


package de.unipassau.medspace.wrapper.image_wrapper.config.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import de.unipassau.medspace.common.rdf.mapping.DataTypePropertyMapping;
import de.unipassau.medspace.common.rdf.mapping.FileMapping;
import de.unipassau.medspace.common.rdf.mapping.ObjectPropertyMapping;


/**
 * <p>Java class for IcsFile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IcsFile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.medspace.com/rdf-mapping}File">
 *       &lt;sequence>
 *         &lt;element name="dateOfStudy" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="patientAge" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="density" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="dateDigitized" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="digitizer" type="{http://www.medspace.com/rdf-mapping}DataTypeProperty"/>
 *         &lt;element name="left_cc" type="{http://www.medspace.com/rdf-mapping}ObjectProperty"/>
 *         &lt;element name="left_mlo" type="{http://www.medspace.com/rdf-mapping}ObjectProperty"/>
 *         &lt;element name="right_cc" type="{http://www.medspace.com/rdf-mapping}ObjectProperty"/>
 *         &lt;element name="right_mlo" type="{http://www.medspace.com/rdf-mapping}ObjectProperty"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IcsFile", propOrder = {
    "dateOfStudy",
    "patientAge",
    "density",
    "dateDigitized",
    "digitizer",
    "leftCc",
    "leftMlo",
    "rightCc",
    "rightMlo"
})
public class IcsFileMapping
    extends FileMapping
{

    @XmlElement(required = true)
    protected DataTypePropertyMapping dateOfStudy;
    @XmlElement(required = true)
    protected DataTypePropertyMapping patientAge;
    @XmlElement(required = true)
    protected DataTypePropertyMapping density;
    @XmlElement(required = true)
    protected DataTypePropertyMapping dateDigitized;
    @XmlElement(required = true)
    protected DataTypePropertyMapping digitizer;
    @XmlElement(name = "left_cc", required = true)
    protected ObjectPropertyMapping leftCc;
    @XmlElement(name = "left_mlo", required = true)
    protected ObjectPropertyMapping leftMlo;
    @XmlElement(name = "right_cc", required = true)
    protected ObjectPropertyMapping rightCc;
    @XmlElement(name = "right_mlo", required = true)
    protected ObjectPropertyMapping rightMlo;

    /**
     * Gets the value of the dateOfStudy property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getDateOfStudy() {
        return dateOfStudy;
    }

    /**
     * Sets the value of the dateOfStudy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setDateOfStudy(DataTypePropertyMapping value) {
        this.dateOfStudy = value;
    }

    /**
     * Gets the value of the patientAge property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getPatientAge() {
        return patientAge;
    }

    /**
     * Sets the value of the patientAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setPatientAge(DataTypePropertyMapping value) {
        this.patientAge = value;
    }

    /**
     * Gets the value of the density property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getDensity() {
        return density;
    }

    /**
     * Sets the value of the density property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setDensity(DataTypePropertyMapping value) {
        this.density = value;
    }

    /**
     * Gets the value of the dateDigitized property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getDateDigitized() {
        return dateDigitized;
    }

    /**
     * Sets the value of the dateDigitized property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setDateDigitized(DataTypePropertyMapping value) {
        this.dateDigitized = value;
    }

    /**
     * Gets the value of the digitizer property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public DataTypePropertyMapping getDigitizer() {
        return digitizer;
    }

    /**
     * Sets the value of the digitizer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyMapping }
     *     
     */
    public void setDigitizer(DataTypePropertyMapping value) {
        this.digitizer = value;
    }

    /**
     * Gets the value of the leftCc property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public ObjectPropertyMapping getLeftCc() {
        return leftCc;
    }

    /**
     * Sets the value of the leftCc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public void setLeftCc(ObjectPropertyMapping value) {
        this.leftCc = value;
    }

    /**
     * Gets the value of the leftMlo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public ObjectPropertyMapping getLeftMlo() {
        return leftMlo;
    }

    /**
     * Sets the value of the leftMlo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public void setLeftMlo(ObjectPropertyMapping value) {
        this.leftMlo = value;
    }

    /**
     * Gets the value of the rightCc property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public ObjectPropertyMapping getRightCc() {
        return rightCc;
    }

    /**
     * Sets the value of the rightCc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public void setRightCc(ObjectPropertyMapping value) {
        this.rightCc = value;
    }

    /**
     * Gets the value of the rightMlo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public ObjectPropertyMapping getRightMlo() {
        return rightMlo;
    }

    /**
     * Sets the value of the rightMlo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPropertyMapping }
     *     
     */
    public void setRightMlo(ObjectPropertyMapping value) {
        this.rightMlo = value;
    }

}
