//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.31 at 07:14:42 PM CEST 
//


package de.unipassau.medspace.global.config.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataCollector complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataCollector">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NativeStoreDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataCollector", propOrder = {
    "nativeStoreDirectory"
})
public class DataCollectorMapping {

    @XmlElement(name = "NativeStoreDirectory", required = true)
    protected String nativeStoreDirectory;

    /**
     * Gets the value of the nativeStoreDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNativeStoreDirectory() {
        return nativeStoreDirectory;
    }

    /**
     * Sets the value of the nativeStoreDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNativeStoreDirectory(String value) {
        this.nativeStoreDirectory = value;
    }

}
