//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.31 at 07:14:42 PM CEST 
//


package de.unipassau.medspace.global.config.mapping;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.unipassau.medspace.global.config.mapping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.unipassau.medspace.global.config.mapping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigMapping }
     * 
     */
    public ConfigMapping createConfigMapping() {
        return new ConfigMapping();
    }

    /**
     * Create an instance of {@link RegisterMapping }
     * 
     */
    public RegisterMapping createRegisterMapping() {
        return new RegisterMapping();
    }

    /**
     * Create an instance of {@link QueryExecutorMapping }
     * 
     */
    public QueryExecutorMapping createQueryExecutorMapping() {
        return new QueryExecutorMapping();
    }

    /**
     * Create an instance of {@link DataCollectorMapping }
     * 
     */
    public DataCollectorMapping createDataCollectorMapping() {
        return new DataCollectorMapping();
    }

}
