//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.31 at 09:49:58 PM CEST 
//


package de.unipassau.medspace.global.config.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryExecutor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryExecutor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataCollectorBaseURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegisterBaseURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryExecutor", propOrder = {
    "dataCollectorBaseURL",
    "registerBaseURL"
})
public class QueryExecutorMapping {

    @XmlElement(name = "DataCollectorBaseURL", required = true)
    protected String dataCollectorBaseURL;
    @XmlElement(name = "RegisterBaseURL", required = true)
    protected String registerBaseURL;

    /**
     * Gets the value of the dataCollectorBaseURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCollectorBaseURL() {
        return dataCollectorBaseURL;
    }

    /**
     * Sets the value of the dataCollectorBaseURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCollectorBaseURL(String value) {
        this.dataCollectorBaseURL = value;
    }

    /**
     * Gets the value of the registerBaseURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterBaseURL() {
        return registerBaseURL;
    }

    /**
     * Sets the value of the registerBaseURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterBaseURL(String value) {
        this.registerBaseURL = value;
    }

}
