//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.06 at 05:19:16 PM CET 
//


package de.unipassau.medspace.wrapper.image_wrapper.config.parsing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Class complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Class">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="rdfType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Class")
@XmlSeeAlso({
    MassParsing.class,
    CalcificationParsing.class,
    IcsFileParsing.class,
    ImageParsing.class,
    OverlayParsing.class,
    AbnormalityParsing.class
})
public class ClassParsing {

    @XmlAttribute(name = "rdfType", required = true)
    protected String rdfType;
    @XmlAttribute(name = "classId", required = true)
    protected String classId;

    /**
     * Gets the value of the rdfType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRdfType() {
        return rdfType;
    }

    /**
     * Sets the value of the rdfType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRdfType(String value) {
        this.rdfType = value;
    }

    /**
     * Gets the value of the classId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassId() {
        return classId;
    }

    /**
     * Sets the value of the classId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassId(String value) {
        this.classId = value;
    }

}
