//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.04 at 04:12:07 PM CET 
//


package de.unipassau.medspace.wrapper.image_wrapper.config.parsing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IcsFile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IcsFile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateOfStudy" type="{http://www.medspace.com/images/ddsm}DataTypeProperty"/>
 *         &lt;element name="patientAge" type="{http://www.medspace.com/images/ddsm}DataTypeProperty"/>
 *         &lt;element name="density" type="{http://www.medspace.com/images/ddsm}DataTypeProperty"/>
 *         &lt;element name="dateDigitized" type="{http://www.medspace.com/images/ddsm}DataTypeProperty"/>
 *         &lt;element name="digitizer" type="{http://www.medspace.com/images/ddsm}DataTypeProperty"/>
 *         &lt;element name="left_cc" type="{http://www.medspace.com/images/ddsm}ObjectProperty"/>
 *         &lt;element name="left_mlo" type="{http://www.medspace.com/images/ddsm}ObjectProperty"/>
 *         &lt;element name="right_cc" type="{http://www.medspace.com/images/ddsm}ObjectProperty"/>
 *         &lt;element name="right_mlo" type="{http://www.medspace.com/images/ddsm}ObjectProperty"/>
 *       &lt;/sequence>
 *       &lt;attribute name="objectType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IcsFile", propOrder = {
    "dateOfStudy",
    "patientAge",
    "density",
    "dateDigitized",
    "digitizer",
    "leftCc",
    "leftMlo",
    "rightCc",
    "rightMlo"
})
public class IcsFileParsing {

    @XmlElement(required = true)
    protected DataTypePropertyParsing dateOfStudy;
    @XmlElement(required = true)
    protected DataTypePropertyParsing patientAge;
    @XmlElement(required = true)
    protected DataTypePropertyParsing density;
    @XmlElement(required = true)
    protected DataTypePropertyParsing dateDigitized;
    @XmlElement(required = true)
    protected DataTypePropertyParsing digitizer;
    @XmlElement(name = "left_cc", required = true)
    protected ObjectProperty leftCc;
    @XmlElement(name = "left_mlo", required = true)
    protected ObjectProperty leftMlo;
    @XmlElement(name = "right_cc", required = true)
    protected ObjectProperty rightCc;
    @XmlElement(name = "right_mlo", required = true)
    protected ObjectProperty rightMlo;
    @XmlAttribute(name = "objectType", required = true)
    protected String objectType;

    /**
     * Gets the value of the dateOfStudy property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public DataTypePropertyParsing getDateOfStudy() {
        return dateOfStudy;
    }

    /**
     * Sets the value of the dateOfStudy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public void setDateOfStudy(DataTypePropertyParsing value) {
        this.dateOfStudy = value;
    }

    /**
     * Gets the value of the patientAge property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public DataTypePropertyParsing getPatientAge() {
        return patientAge;
    }

    /**
     * Sets the value of the patientAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public void setPatientAge(DataTypePropertyParsing value) {
        this.patientAge = value;
    }

    /**
     * Gets the value of the density property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public DataTypePropertyParsing getDensity() {
        return density;
    }

    /**
     * Sets the value of the density property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public void setDensity(DataTypePropertyParsing value) {
        this.density = value;
    }

    /**
     * Gets the value of the dateDigitized property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public DataTypePropertyParsing getDateDigitized() {
        return dateDigitized;
    }

    /**
     * Sets the value of the dateDigitized property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public void setDateDigitized(DataTypePropertyParsing value) {
        this.dateDigitized = value;
    }

    /**
     * Gets the value of the digitizer property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public DataTypePropertyParsing getDigitizer() {
        return digitizer;
    }

    /**
     * Sets the value of the digitizer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public void setDigitizer(DataTypePropertyParsing value) {
        this.digitizer = value;
    }

    /**
     * Gets the value of the leftCc property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectProperty }
     *     
     */
    public ObjectProperty getLeftCc() {
        return leftCc;
    }

    /**
     * Sets the value of the leftCc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectProperty }
     *     
     */
    public void setLeftCc(ObjectProperty value) {
        this.leftCc = value;
    }

    /**
     * Gets the value of the leftMlo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectProperty }
     *     
     */
    public ObjectProperty getLeftMlo() {
        return leftMlo;
    }

    /**
     * Sets the value of the leftMlo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectProperty }
     *     
     */
    public void setLeftMlo(ObjectProperty value) {
        this.leftMlo = value;
    }

    /**
     * Gets the value of the rightCc property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectProperty }
     *     
     */
    public ObjectProperty getRightCc() {
        return rightCc;
    }

    /**
     * Sets the value of the rightCc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectProperty }
     *     
     */
    public void setRightCc(ObjectProperty value) {
        this.rightCc = value;
    }

    /**
     * Gets the value of the rightMlo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectProperty }
     *     
     */
    public ObjectProperty getRightMlo() {
        return rightMlo;
    }

    /**
     * Sets the value of the rightMlo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectProperty }
     *     
     */
    public void setRightMlo(ObjectProperty value) {
        this.rightMlo = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectType(String value) {
        this.objectType = value;
    }

}
