//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.06 at 05:19:16 PM CET 
//


package de.unipassau.medspace.wrapper.image_wrapper.config.parsing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Overlay complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Overlay">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.medspace.com/images/ddsm}Class">
 *       &lt;sequence>
 *         &lt;element name="totalAbnormalities" type="{http://www.medspace.com/images/ddsm}DataTypeProperty"/>
 *         &lt;element name="abnormality" type="{http://www.medspace.com/images/ddsm}ObjectProperty"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Overlay", propOrder = {
    "totalAbnormalities",
    "abnormality"
})
public class OverlayParsing
    extends ClassParsing
{

    @XmlElement(required = true)
    protected DataTypePropertyParsing totalAbnormalities;
    @XmlElement(required = true)
    protected ObjectProperty abnormality;

    /**
     * Gets the value of the totalAbnormalities property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public DataTypePropertyParsing getTotalAbnormalities() {
        return totalAbnormalities;
    }

    /**
     * Sets the value of the totalAbnormalities property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypePropertyParsing }
     *     
     */
    public void setTotalAbnormalities(DataTypePropertyParsing value) {
        this.totalAbnormalities = value;
    }

    /**
     * Gets the value of the abnormality property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectProperty }
     *     
     */
    public ObjectProperty getAbnormality() {
        return abnormality;
    }

    /**
     * Sets the value of the abnormality property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectProperty }
     *     
     */
    public void setAbnormality(ObjectProperty value) {
        this.abnormality = value;
    }

}
