//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.06 at 05:19:16 PM CET 
//


package de.unipassau.medspace.wrapper.image_wrapper.config.parsing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Root element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Root">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="Namespace" type="{http://www.medspace.com/images/ddsm}Namespace" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="IcsFile" type="{http://www.medspace.com/images/ddsm}IcsFile"/>
 *           &lt;element name="Image" type="{http://www.medspace.com/images/ddsm}Image"/>
 *           &lt;element name="Overlay" type="{http://www.medspace.com/images/ddsm}Overlay"/>
 *           &lt;element name="Abnormality" type="{http://www.medspace.com/images/ddsm}Abnormality"/>
 *           &lt;element name="Calcification" type="{http://www.medspace.com/images/ddsm}Calcification"/>
 *           &lt;element name="Mass" type="{http://www.medspace.com/images/ddsm}Mass"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namespace",
    "icsFile",
    "image",
    "overlay",
    "abnormality",
    "calcification",
    "mass"
})
@XmlRootElement(name = "Root")
public class RootParsing {

    @XmlElement(name = "Namespace")
    protected List<NamespaceParsing> namespace;
    @XmlElement(name = "IcsFile", required = true)
    protected IcsFileParsing icsFile;
    @XmlElement(name = "Image", required = true)
    protected ImageParsing image;
    @XmlElement(name = "Overlay", required = true)
    protected OverlayParsing overlay;
    @XmlElement(name = "Abnormality", required = true)
    protected AbnormalityParsing abnormality;
    @XmlElement(name = "Calcification", required = true)
    protected CalcificationParsing calcification;
    @XmlElement(name = "Mass", required = true)
    protected MassParsing mass;

    /**
     * Gets the value of the namespace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namespace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamespace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NamespaceParsing }
     * 
     * 
     */
    public List<NamespaceParsing> getNamespace() {
        if (namespace == null) {
            namespace = new ArrayList<NamespaceParsing>();
        }
        return this.namespace;
    }

    /**
     * Gets the value of the icsFile property.
     * 
     * @return
     *     possible object is
     *     {@link IcsFileParsing }
     *     
     */
    public IcsFileParsing getIcsFile() {
        return icsFile;
    }

    /**
     * Sets the value of the icsFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcsFileParsing }
     *     
     */
    public void setIcsFile(IcsFileParsing value) {
        this.icsFile = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link ImageParsing }
     *     
     */
    public ImageParsing getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageParsing }
     *     
     */
    public void setImage(ImageParsing value) {
        this.image = value;
    }

    /**
     * Gets the value of the overlay property.
     * 
     * @return
     *     possible object is
     *     {@link OverlayParsing }
     *     
     */
    public OverlayParsing getOverlay() {
        return overlay;
    }

    /**
     * Sets the value of the overlay property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverlayParsing }
     *     
     */
    public void setOverlay(OverlayParsing value) {
        this.overlay = value;
    }

    /**
     * Gets the value of the abnormality property.
     * 
     * @return
     *     possible object is
     *     {@link AbnormalityParsing }
     *     
     */
    public AbnormalityParsing getAbnormality() {
        return abnormality;
    }

    /**
     * Sets the value of the abnormality property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbnormalityParsing }
     *     
     */
    public void setAbnormality(AbnormalityParsing value) {
        this.abnormality = value;
    }

    /**
     * Gets the value of the calcification property.
     * 
     * @return
     *     possible object is
     *     {@link CalcificationParsing }
     *     
     */
    public CalcificationParsing getCalcification() {
        return calcification;
    }

    /**
     * Sets the value of the calcification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalcificationParsing }
     *     
     */
    public void setCalcification(CalcificationParsing value) {
        this.calcification = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link MassParsing }
     *     
     */
    public MassParsing getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassParsing }
     *     
     */
    public void setMass(MassParsing value) {
        this.mass = value;
    }

}
