//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.02 at 12:36:13 AM CEST 
//


package de.unipassau.medspace.wrapper.image_wrapper.config.mapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import de.unipassau.medspace.common.rdf.mapping.NamespaceMapping;


/**
 * <p>Java class for Root element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Root">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="Namespace" type="{http://www.medspace.com/rdf-mapping}Namespace" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="IcsFile" type="{http://www.medspace.com/images/ddsm}IcsFile"/>
 *           &lt;element name="Image" type="{http://www.medspace.com/images/ddsm}Image"/>
 *           &lt;element name="Overlay" type="{http://www.medspace.com/images/ddsm}Overlay"/>
 *           &lt;element name="Abnormality" type="{http://www.medspace.com/images/ddsm}Abnormality"/>
 *           &lt;element name="Calcification" type="{http://www.medspace.com/images/ddsm}Calcification"/>
 *           &lt;element name="Mass" type="{http://www.medspace.com/images/ddsm}Mass"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namespace",
    "icsFile",
    "image",
    "overlay",
    "abnormality",
    "calcification",
    "mass"
})
@XmlRootElement(name = "Root")
public class RootMapping {

    @XmlElement(name = "Namespace")
    protected List<NamespaceMapping> namespace;
    @XmlElement(name = "IcsFile", required = true)
    protected IcsFileMapping icsFile;
    @XmlElement(name = "Image", required = true)
    protected ImageMapping image;
    @XmlElement(name = "Overlay", required = true)
    protected OverlayMapping overlay;
    @XmlElement(name = "Abnormality", required = true)
    protected AbnormalityMapping abnormality;
    @XmlElement(name = "Calcification", required = true)
    protected CalcificationMapping calcification;
    @XmlElement(name = "Mass", required = true)
    protected MassMapping mass;

    /**
     * Gets the value of the namespace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namespace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamespace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NamespaceMapping }
     * 
     * 
     */
    public List<NamespaceMapping> getNamespace() {
        if (namespace == null) {
            namespace = new ArrayList<NamespaceMapping>();
        }
        return this.namespace;
    }

    /**
     * Gets the value of the icsFile property.
     * 
     * @return
     *     possible object is
     *     {@link IcsFileMapping }
     *     
     */
    public IcsFileMapping getIcsFile() {
        return icsFile;
    }

    /**
     * Sets the value of the icsFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcsFileMapping }
     *     
     */
    public void setIcsFile(IcsFileMapping value) {
        this.icsFile = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link ImageMapping }
     *     
     */
    public ImageMapping getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageMapping }
     *     
     */
    public void setImage(ImageMapping value) {
        this.image = value;
    }

    /**
     * Gets the value of the overlay property.
     * 
     * @return
     *     possible object is
     *     {@link OverlayMapping }
     *     
     */
    public OverlayMapping getOverlay() {
        return overlay;
    }

    /**
     * Sets the value of the overlay property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverlayMapping }
     *     
     */
    public void setOverlay(OverlayMapping value) {
        this.overlay = value;
    }

    /**
     * Gets the value of the abnormality property.
     * 
     * @return
     *     possible object is
     *     {@link AbnormalityMapping }
     *     
     */
    public AbnormalityMapping getAbnormality() {
        return abnormality;
    }

    /**
     * Sets the value of the abnormality property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbnormalityMapping }
     *     
     */
    public void setAbnormality(AbnormalityMapping value) {
        this.abnormality = value;
    }

    /**
     * Gets the value of the calcification property.
     * 
     * @return
     *     possible object is
     *     {@link CalcificationMapping }
     *     
     */
    public CalcificationMapping getCalcification() {
        return calcification;
    }

    /**
     * Sets the value of the calcification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalcificationMapping }
     *     
     */
    public void setCalcification(CalcificationMapping value) {
        this.calcification = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link MassMapping }
     *     
     */
    public MassMapping getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassMapping }
     *     
     */
    public void setMass(MassMapping value) {
        this.mass = value;
    }

}
